### ISSUE TITLE
import megbrain to avoid dead lock bug

### ISSUE THREAD

**Issue by wxy1234567** [megvii-research/HDR-Transformer#1]
Hi,, thank you for your excellent work.  I'm a newcomer to megengine.  When I execute the training script, there is a "lock" situation. I don't know what caused it. I only modified the data set path in the params.json ,  and line 13 in evaluate.py are shielded.

**Comment by liuzhen03** [comment]
Hi, Thanks.
Can you provide more details of the training log? If you get stuck in the training/validation stage, you can disable the [DTR](https://www.megengine.org.cn/doc/stable/zh/user-guide/model-development/dtr/index.html?highlight=dtr) in train.py. 
```
# mge.dtr.enable()
```

**Comment by wxy1234567** [comment]
Thank you for your reply, now it works normally.
