### ISSUE TITLE
pip install MegEngine==1.8.3

### ISSUE THREAD

**Issue by hangxiaotian** [megvii-research/HDR-Transformer#4]
ERROR: No matching distribution found for MegEngine==1.8.3

The [url](https://www.megengine.org.cn/whl/mge.html) does not have version 1.8.3 of MegEngine.

**Comment by liuzhen03** [comment]
The missing version may have been removed, please try a newer version.

**Comment by wahaha** [comment]
Which version of cuda are you running on? And Which platform are you running on? Windows or linux?
